package offlinepkg

import (
	"crypto/ed25519"
	"encoding/base64"
	"fmt"
	"sync"
	"time"
)

// MemoryTrustStore is an in-memory, thread-safe implementation of TrustStore.
type MemoryTrustStore struct {
	mu    sync.RWMutex
	keys  map[string]TrustedKey
	nowFn func() time.Time
}

// NewTrustStore initializes a MemoryTrustStore with the provided trusted keys.
func NewTrustStore(keys ...TrustedKey) *MemoryTrustStore {
	store := &MemoryTrustStore{
		keys:  make(map[string]TrustedKey, len(keys)),
		nowFn: func() time.Time { return time.Now().UTC() },
	}
	for _, k := range keys {
		_ = store.AddKey(k)
	}
	return store
}

// WithClock overrides the clock function for deterministic testing of key validity.
func (s *MemoryTrustStore) WithClock(fn func() time.Time) *MemoryTrustStore {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.nowFn = fn
	return s
}

// AddKey registers or updates a trusted authority key.
func (s *MemoryTrustStore) AddKey(k TrustedKey) error {
	if k.KeyID == "" {
		return fmt.Errorf("%w: key_id cannot be empty", ErrSignerUnauthorized)
	}
	if len(k.PublicKey) != ed25519.PublicKeySize {
		return fmt.Errorf("%w: invalid ed25519 public key size %d", ErrInvalidSignature, len(k.PublicKey))
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.keys[k.KeyID] = k
	return nil
}

// RevokeKey marks an existing key as revoked.
func (s *MemoryTrustStore) RevokeKey(keyID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	k, ok := s.keys[keyID]
	if !ok {
		return fmt.Errorf("%w: key %q not found", ErrUnknownKey, keyID)
	}
	k.Revoked = true
	s.keys[keyID] = k
	return nil
}

// LookupKey retrieves a key by its identifier.
func (s *MemoryTrustStore) LookupKey(keyID string) (TrustedKey, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	k, ok := s.keys[keyID]
	if !ok {
		return TrustedKey{}, fmt.Errorf("%w: key %q not found in trust store", ErrUnknownKey, keyID)
	}
	return k, nil
}

// VerifySignature verifies that sigBase64 was generated by keyID over canonicalBytes,
// that keyID is authorized for jurisdiction, is unexpired, and is not revoked.
func (s *MemoryTrustStore) VerifySignature(keyID, jurisdiction string, canonicalBytes []byte, sigBase64 string) error {
	s.mu.RLock()
	now := s.nowFn()
	s.mu.RUnlock()
	return s.VerifySignatureAt(keyID, jurisdiction, canonicalBytes, sigBase64, now)
}

// VerifySignatureAt verifies the signature against a specific instant in time.
func (s *MemoryTrustStore) VerifySignatureAt(keyID, jurisdiction string, canonicalBytes []byte, sigBase64 string, at time.Time) error {
	k, err := s.LookupKey(keyID)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrSignerUnauthorized, err)
	}

	if k.Revoked {
		return fmt.Errorf("%w: key %q is revoked", ErrSignerUnauthorized, keyID)
	}

	// Wildcard "*" permitted only in test harnesses; otherwise jurisdiction must match exactly.
	if k.PermittedJurisdiction != "*" && k.PermittedJurisdiction != jurisdiction {
		return fmt.Errorf("%w: key %q permitted for %q but document is for %q",
			ErrSignerUnauthorized, keyID, k.PermittedJurisdiction, jurisdiction)
	}

	if !k.ValidFrom.IsZero() && at.Before(k.ValidFrom) {
		return fmt.Errorf("%w: key %q not valid before %v", ErrKeyExpired, keyID, k.ValidFrom)
	}
	if !k.ValidUntil.IsZero() && at.After(k.ValidUntil) {
		return fmt.Errorf("%w: key %q expired at %v", ErrKeyExpired, keyID, k.ValidUntil)
	}

	sigBytes, err := base64.StdEncoding.DecodeString(sigBase64)
	if err != nil || len(sigBytes) != ed25519.SignatureSize {
		return fmt.Errorf("%w: base64 decode failed or invalid signature size", ErrInvalidSignature)
	}

	if !ed25519.Verify(k.PublicKey, canonicalBytes, sigBytes) {
		return ErrInvalidSignature
	}

	return nil
}
