"""
Sthira Shared Domain Core Package (PKG-0C).
"""

from sthira.core.enums import (
    GateState,
    AuthorityState,
    RelocationPathway,
    FundingState,
    DiscrepancyType,
    SourceCapability,
    SourceActivationState,
    DecisionState,
    ConsentPurpose,
    SolverStatus,
    RoleType,
    ClassificationLevel,
)
from sthira.core.contracts import (
    BitemporalRecord,
    GeographyScope,
    UserContext,
    GeoPoint,
    GeoPolygon,
    GeoMultiPolygon,
    SourceMetadata,
    HardGateResult,
    DimensionScore,
    AdvisoryEnvelope,
    AuditEntry,
    APIResponseEnvelope,
)
from sthira.core.errors import (
    SthiraError,
    AuthorityBypassError,
    MissingEvidenceError,
    HardGateBlockedError,
    MasterScoreProhibitedError,
    OutOfCoverageError,
    UnauthorizedGeographyAccessError,
    AuditIntegrityError,
    CapacityExceededError,
)
from sthira.core.audit import AuditLedger, global_audit_ledger
from sthira.core.outbox import TransactionalOutbox, OutboxMessage, OutboxStatus, global_outbox

__all__ = [
    "GateState",
    "AuthorityState",
    "RelocationPathway",
    "FundingState",
    "DiscrepancyType",
    "SourceCapability",
    "SourceActivationState",
    "DecisionState",
    "ConsentPurpose",
    "SolverStatus",
    "RoleType",
    "ClassificationLevel",
    "BitemporalRecord",
    "GeographyScope",
    "UserContext",
    "GeoPoint",
    "GeoPolygon",
    "GeoMultiPolygon",
    "SourceMetadata",
    "HardGateResult",
    "DimensionScore",
    "AdvisoryEnvelope",
    "AuditEntry",
    "APIResponseEnvelope",
    "SthiraError",
    "AuthorityBypassError",
    "MissingEvidenceError",
    "HardGateBlockedError",
    "MasterScoreProhibitedError",
    "OutOfCoverageError",
    "UnauthorizedGeographyAccessError",
    "AuditIntegrityError",
    "CapacityExceededError",
    "AuditLedger",
    "global_audit_ledger",
    "TransactionalOutbox",
    "OutboxMessage",
    "OutboxStatus",
    "global_outbox",
]
